const unitOptions = [
  // Volume (US)
  { value: "teaspoon", label: "Teaspoon" },
  { value: "tablespoon", label: "Tablespoon" },
  { value: "fluid_ounce", label: "Fluid Ounce" },
  { value: "cup", label: "Cup" },
  { value: "pint", label: "Pint" },
  { value: "quart", label: "Quart" },
  { value: "gallon", label: "Gallon" },

  // Volume (Metric)
  { value: "milliliter", label: "Milliliter" },
  { value: "liter", label: "Liter" },

  // Weight
  { value: "milligram", label: "Milligram" },
  { value: "gram", label: "Gram" },
  { value: "kilogram", label: "Kilogram" },
  { value: "ounce", label: "Ounce" },
  { value: "pound", label: "Pound" },

  // Length (rare but sometimes used for pasta etc.)
  { value: "inch", label: "Inch" },
  { value: "centimeter", label: "Centimeter" },

  // Count-based units
  { value: "clove", label: "Clove" },
  { value: "piece", label: "Piece" },
  { value: "slice", label: "Slice" },
  { value: "can", label: "Can" },
  { value: "bunch", label: "Bunch" },
  { value: "stick", label: "Stick" },
  { value: "pinch", label: "Pinch" },
  { value: "dash", label: "Dash" },
  { value: "sprig", label: "Sprig" },
  { value: "head", label: "Head" },
  { value: "package", label: "Package" },
  { value: "jar", label: "Jar" },
  { value: "bag", label: "Bag" },
  { value: "bottle", label: "Bottle" },
  { value: "drop", label: "Drop" },
];

const ingredientOptions = [
  { value: "chicken", label: "Chicken" },
  { value: "beef", label: "Beef" },
  { value: "turkey", label: "Turkey" },
  { value: "pork", label: "Pork" },
  { value: "salmon", label: "Salmon" },
  { value: "shrimp", label: "Shrimp" },
  { value: "eggs", label: "Eggs" },
  { value: "milk", label: "Milk" },
  { value: "heavy_cream", label: "Heavy Whipping Cream" },
  { value: "butter", label: "Butter" },
  { value: "cheddar_cheese", label: "Cheddar Cheese" },
  { value: "mozzarella_cheese", label: "Mozzarella Cheese" },
  { value: "parmesan_cheese", label: "Parmesan Cheese" },
  { value: "tomatoes", label: "Tomatoes" },
  { value: "onions", label: "Onions" },
  { value: "garlic", label: "Garlic" },
  { value: "carrots", label: "Carrots" },
  { value: "celery", label: "Celery" },
  { value: "potatoes", label: "Potatoes" },
  { value: "bell_peppers", label: "Bell Peppers" },
  { value: "spinach", label: "Spinach" },
  { value: "lettuce", label: "Lettuce" },
  { value: "broccoli", label: "Broccoli" },
  { value: "mushrooms", label: "Mushrooms" },
  { value: "olive_oil", label: "Olive Oil" },
  { value: "vegetable_oil", label: "Vegetable Oil" },
  { value: "salt", label: "Salt" },
  { value: "black_pepper", label: "Black Pepper" },
  { value: "sugar", label: "Sugar" },
  { value: "flour", label: "Flour" },
  { value: "baking_powder", label: "Baking Powder" },
  { value: "baking_soda", label: "Baking Soda" },
  { value: "vanilla_extract", label: "Vanilla Extract" },
  { value: "honey", label: "Honey" },
  { value: "soy_sauce", label: "Soy Sauce" },
  { value: "rice", label: "Rice" },
  { value: "pasta", label: "Pasta" },
  { value: "bread", label: "Bread" },
  { value: "cinnamon", label: "Cinnamon" },
  { value: "nutmeg", label: "Nutmeg" },
  { value: "cumin", label: "Cumin" },
  { value: "paprika", label: "Paprika" },
  { value: "oregano", label: "Oregano" },
  { value: "basil", label: "Basil" },
  { value: "thyme", label: "Thyme" },
  { value: "chili_powder", label: "Chili Powder" },
  { value: "coriander", label: "Coriander" },
];

export { unitOptions, ingredientOptions };
